### Name:-Prachi Balaji Upare
### Roll no.:-2447053
### Batch:-C
### Practical No.6:- Build a Tic-Tac-Toe game using reinforcement learning in Python by using following tasks 
                       a. Setting up the environment
                       b. Defining the Tic-Tac-Toe game 
                       c. Building the reinforcement learning model 
                       d. Training the model e. Testing the model 

In [1]:
import numpy as np

class TicTacToe:
    def __init__(self): self.board = np.zeros((3, 3)); self.done = False
    def reset(self): self.board = np.zeros((3, 3)); self.done = False; return self.board
    def check_winner(self):  # Check rows, cols, diagonals for a winner or draw
        for i in range(3):
            if np.all(self.board[i, :] == 1) or np.all(self.board[:, i] == 1): self.done = True; return 1
            if np.all(self.board[i, :] == -1) or np.all(self.board[:, i] == -1): self.done = True; return -1
        if np.all(np.diag(self.board) == 1) or np.all(np.diag(np.fliplr(self.board)) == 1): self.done = True; return 1
        if np.all(np.diag(self.board) == -1) or np.all(np.diag(np.fliplr(self.board)) == -1): self.done = True; return -1
        if not np.any(self.board == 0): self.done = True; return 0
    def step(self, action, player): self.board[action // 3, action % 3] = player; return self.board, self.check_winner()

class QLearningAgent:
    def __init__(self, epsilon=0.1, alpha=0.5, gamma=0.9): self.q = {}; self.eps = epsilon; self.alpha = alpha; self.gamma = gamma
    def get_q(self, state, action): return self.q.get((state, action), 0)
    def choose_action(self, state, valid): return np.random.choice(valid) if np.random.rand() < self.eps else valid[np.argmax([self.get_q(state, a) for a in valid])]
    def update_q(self, state, action, reward, next_state, valid): best_next = max([self.get_q(next_state, a) for a in valid], default=0); self.q[(state, action)] = self.get_q(state, action) + self.alpha * (reward + self.gamma * best_next - self.get_q(state, action))

def train(agent, episodes=1000):
    env = TicTacToe()
    for _ in range(episodes):
        state = env.reset().flatten().tobytes(); player = 1
        while not env.done:
            valid = [i for i in range(9) if env.board[i // 3, i % 3] == 0]
            action = agent.choose_action(state, valid)
            next_state, winner = env.step(action, player)
            reward = 1 if winner == player else -1 if winner == -player else 0
            agent.update_q(state, action, reward, next_state.flatten().tobytes(), valid)
            state, player = next_state.flatten().tobytes(), -player

def test(agent):
    env = TicTacToe(); state = env.reset().flatten().tobytes(); player = 1
    while not env.done:
        valid = [i for i in range(9) if env.board[i // 3, i % 3] == 0]
        action = agent.choose_action(state, valid) if player == 1 else int(input("Your move (0-8): "))
        _, winner = env.step(action, player)
        print(env.board)
        if winner is not None:  # Stop the game when there is a winner or draw
            if winner == 1: print("Agent wins!")
            elif winner == -1: print("You win!")
            else: print("It's a draw!")
            break
        state, player = env.board.flatten().tobytes(), -player

agent = QLearningAgent()
train(agent)
test(agent)


[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Your move (0-8): 4
[[ 1.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]
Your move (0-8): 2
[[ 1.  1. -1.]
 [ 0. -1.  0.]
 [ 0.  0.  0.]]
[[ 1.  1. -1.]
 [ 1. -1.  0.]
 [ 0.  0.  0.]]
Your move (0-8): 6
[[ 1.  1. -1.]
 [ 1. -1.  0.]
 [-1.  0.  0.]]
You win!
